#! /bin/sh

name=base-files
version=0.0
revision=1
source_dir="base-files"
skip_pkg_check=yes
package() {
  cp -rpv ${source_dir}/. "${dest_dir}"/
    mkdir -pv "${dest_dir}/home/nyaux"

ln -s usr/bin "${dest_dir}"/bin
    ln -s usr/bin "${dest_dir}"/sbin
    ln -s usr/lib "${dest_dir}"/lib
    ln -s usr/lib "${dest_dir}"/lib64
    ln -s bin "${dest_dir}"/usr/sbin
    ln -s lib "${dest_dir}"/usr/lib64

   

}
