#! /bin/sh

name=kernel
version=0.0git
revision=1
source_dir="kernel"
source_imagedeps="git"
source_allow_network=yes
allow_network=yes
hostdeps="gcc pkg-config libgcc-binaries"
imagedeps="git nasm build-essential meson ninja-build cmake"
deps="core-libs"
builddeps="freestnd-c-hdrs freestnd-cxx-hdrs frigg"

prepare() {
    ./get-deps
    mkdir -p ${source_dir}/subprojects

}
configure() {
    LDFLAGS="-Wl,/usr/local/libgcc-binaries/libgcc-$ARCHITECTURE.a" \
    meson_configure_noflags \
        --buildtype=debugoptimized
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install
}
