#! /bin/sh

name=mlibc
version=b4fb75b3379762d006e7d9b98fd739778e2d3a21
revision=1
git_url="https://github.com/managarm/mlibc.git"
commit=${version}
imagedeps="build-essential meson ninja-build"
hostdeps="gcc pkg-config libgcc-binaries"
builddeps="freestnd-c-hdrs freestnd-cxx-hdrs frigg"
deps="linux-headers mlibc-headers"

configure() {
        CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS -Wl,/usr/local/libgcc-binaries/libgcc-$ARCHITECTURE.a" \
    meson_configure_noflags \
        --buildtype=release \
        -Dno_headers=true \
        -Dlinux_kernel_headers=${sysroot_dir}${prefix}/include \
        -Dposix_option=enabled \
        -Ddefault_library=both \
        -Dlibgcc_dependency=false \
        -Duse_freestnd_hdrs=enabled
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install
}
