#! /bin/sh

name=mlibc
version=310bf7c75c1a8fbd4b39a06f9b45fdc0b5d78b7a
revision=1
git_url="https://github.com/managarm/mlibc.git"
commit=${version}
imagedeps="meson ninja-build"
hostdeps="gcc pkg-config libgcc-binaries"
builddeps="freestnd-c-hdrs freestnd-cxx-hdrs frigg"
deps="mlibc-headers"

configure() {
        CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS -Wl,/usr/local/libgcc-binaries/libgcc-$ARCHITECTURE.a" \
    meson_configure_noflags \
        --buildtype=release \
        -Dposix_option=enabled \
        -Dno_headers=true \
        -Ddefault_library=both \
        -Dlibgcc_dependency=false \
        -Duse_freestnd_hdrs=enabled
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install
}
