#! /bin/sh

name=ttytest
version=0.0
revision=1
source_dir="ttytest"
imagedeps="meson ninja-build build-essential"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    meson_configure
}
build() {
    ninja -j${parallelism}
}
package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}